### ISSUE TITLE
Suppor for relative paths?

### ISSUE THREAD

**Issue by lffg** [poppinss/edge#51]
How can I include a file using relative paths using Edge?

Example:

```blade
@include('./includes.user-card')
```

Does not work. Then I have to do:
```blade
@include('pages.user.includes.user-card')
```

Thanks a lot if you can help.

**Comment by thetutlage** [comment]
Nope, Edge doesn't support relative paths. There is no technical reasons to it but a matter of preference. 

When you have relative paths, it's harder to move views into different directories, since you have to change the relative references too.

Whereas with current structure, it doesn't matter where in the folder structure your views are, they will always reference other views with absolute paths.

**Comment by lffg** [comment]
Ok, thanks.
